### ISSUE TITLE
Calling search without authentication

### ISSUE THREAD

**Issue by bih** [kabirvirji/singlespotify#2]
Hi @kabirvirji - Spotify's search API [requires authentication](https://beta.developer.spotify.com/community/news/2017/01/27/removing-unauthenticated-calls-to-the-web-api/), but SingleSpotify is calling it without the token. Great hack, it'd be great to see it get updated and work again! 😄

**Comment by kabirvirji** [comment]
@bih haha yeah, I built this before the update to the API. Planning on fixing it when I'm done exams! Thanks for the reminder.

**Comment by kabirvirji** [comment]
@bih I updated the project and republished on `npm`, you can `npm install -g singlespotify` to check it out!
